### PR TITLE
twitter connection

### PR DESCRIPTION
**Pull request by bhargodevarya**
Added twitter connection, was able to open the popup for login

### CODE REVIEW

**Comment by raviten** [comment]
Hey @bhargodevarya , we are still not populating email in twitter authentication. Can you please check it

**Comment by bhargodevarya** [comment]
you mean to say we need to store the emailAddress used for twitter login in firebase DB ??

**Comment by bhargodevarya** [comment]
Enabling the app to request email addresses requires setting in the app.
As per this setting we can only do so if we provide the URL for our terms of usage and privacy policy.

https://github.com/firebase/FirebaseUI-Android/issues/419

**Comment by bhargodevarya** [comment]
screenshot from 2017-08-09 22-12-43

**Comment by raviten** [comment]
I will update T&C's by this weekend. I am afraid that PR has to wait till then

**Comment by raviten** [comment]
Hey @bhargodevarya , I have updated terms and conditions

You can test now

**Pull request merged**
